pipeline{

    agent any

    environment{
        DOCKER_USER = credentials('docker_user')
        DOCKER_PASS = credentials('docker_pass')

        def XYZ='Hello ITI'
    }


    stages{
     
        stage("build Docker image"){
            steps{
                sh ''' echo "${XYZ}" '''
                sh "docker build -t mariam191/python_app:v${BUILD_NUMBER} ."
            }
        }

        stage("push java app image"){
            steps{
                sh "docker push mariam191/python_app:v${BUILD_NUMBER}"
                
            }
        }

    }
    
    post{
        always{
            sh "echo 'Clean the Workspace'"
            cleanWs()
        }
        failure {
            sh "echo 'failed'"
        }
    }
}
