@Library('libx')_

pipeline{

    agent any

    environment{
        DOCKER_USER = credentials('docker_user')
        DOCKER_PASS = credentials('docker_pass')

        def XYZ='Hello Mariam'
    }


    stages{
     
        stage("build Docker image"){
            steps{
                
                // sh ''' echo "${XYZ}" '''
                
                script{
                    // sayHello "Mero!!!!!!!"
                    def VM_IP = vmip()
                    sh "echo ${VM_IP}"

                    def dockerx = new org.ITI.docker()
                    dockerx.build("mariam191/python_app", "${BUILD_NUMBER}")
                }
                
            }
        }

        stage("push java app image"){
            steps{
                 script{
                    sayHello("Mero!!!!!!!")
                    // def VMIP = vmip()
                    // sh "echo ${VMIP}"

                    def dockerx = new org.ITI.docker()
                    dockerx.login("${DOCKER_USER}", "${DOCKER_PASS}")
                    dockerx.push("mariam191/python_app", "${BUILD_NUMBER}")
                }
                
                
            }
        }

    }
    
    post{
        always{
            sh "echo 'Clean the Workspace'"
            cleanWs()
        }
        failure {
            sh "echo 'failed'"
        }
    }
}
